---
- name: Install Prerequisite Packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - mariadb-server

- name: Copy configuration files
  copy:
    src: "{{ item }}"
    dest: /{{ item }}
  with_items:
    - etc/mysql/mariadb.conf.d/50-server.cnf
  notify:
    - restart mariadb
