---
- name: Install Prerequisite Packages
  apt:
    name: "{{ item }}"
    state: latest
  with_items:
    - python3

- name: Copy configuration files
  copy:
    src: "{{ item }}"
    dest: /{{ item }}
  with_items:
    - home/hass/.homeassistant/configuration.yaml
  notify:
    - restart home-assistant
